stages:
  - build

build:
  image: python:3.8.10
  stage: build
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py collectstatic --noinput
    - python manage.py migrate --noinput
