stages:
        - stop_server
        - pull_code
        - start_server

stop_server:
        stage: stop_server
        script:
                - echo "Stopping Django server"
                - kill $(ps aux | grep 'python3 manage.py runserver' | awk '{print $2}')

pull_code:
        stage: pull_code
        script:
                - echo "Pulling latest code from GitLab"
                - git pull origin develop

start_server:
        stage: start_server
        script:
                - echo "Starting Django server"
                - python3 manage.py runserver 0.0.0.0:8000
